// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ZGqiChXiwaeJuGJ08ccS1uoG1eCDQh0',
    appId: '1:111878878990:web:79720066ccf1654b9b495f',
    messagingSenderId: '111878878990',
    projectId: 'ecommercebig',
    authDomain: 'ecommercebig.firebaseapp.com',
    storageBucket: 'ecommercebig.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxnub0C_RIxdWUKMW1V1SN9IwlIw-sNZ0',
    appId: '1:111878878990:android:acdb15dcb34783d49b495f',
    messagingSenderId: '111878878990',
    projectId: 'ecommercebig',
    storageBucket: 'ecommercebig.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0qrVn3yJkKGCbd3GRUJaUTVbQZbPMZ0s',
    appId: '1:111878878990:ios:a0ea57b2dfc808d99b495f',
    messagingSenderId: '111878878990',
    projectId: 'ecommercebig',
    storageBucket: 'ecommercebig.appspot.com',
    iosBundleId: 'com.example.ecommercebig',
  );
}
